extends: airbnb
env:
    browser: true
parser: babel-eslint
globals:
  document: false
  log: false
rules:
  no-return-assign: off
  padded-blocks: off
  react/prefer-stateless-function: off
  react/no-multi-comp: off
  react/forbid-prop-types: off
  prefer-destructuring: warn
  jsx-a11y/anchor-is-valid: warn
  quotes: warn
  space-in-parens: warn
  no-multi-spaces: warn
  arrow-body-style: warn
  object-shorthand: warn
  spaced-comment: warn
  space-infix-ops: warn
  no-unused-vars: warn
  no-trailing-spaces: warn
  class-methods-use-this: off
  no-useless-constructor: warn
  import/no-extraneous-dependencies: warn
  react/jsx-tag-spacing: warn
  react/jsx-indent: warn
  react/no-array-index-key: warn
  react/sort-comp: warn
  react/prop-types: warn
